@startuml Répéteur 169Mhz
    skinparam style strictuml
    skinparam SequenceMessageAlignment center
    entity SIAS
    entity Concentrateur
    entity Répéteur
    entity MOBx
    entity Capteur

    group Phase de pose
        MOBx -> Répéteur : Liste des capteurs à répéter\n, canal de regroupement
        note right : via NFC
    end

    group Phase d'initialisation
        Répéteur -> Répéteur : Ecoute active sur\n les cinq canaux
        note left : pendant 50h pour prendre tous les canaux
        Capteur -> Répéteur : Premier message
        Répéteur -> Capteur : Programmation heure, canal,\n modulation
        note right : Si le capteur est dans\n la liste des capteurs à répéter    
    end

    loop 15 mn chaque jour
        Répéteur -> Répéteur : Ecoute active sur canal\n de regroupement
        Capteur -> Répéteur : Message
        Répéteur -> Concentrateur : Message
        note right : Si le message est dans\n la liste des capteurs à répéter
    end

    group Téléopérations Capteurs
        Concentrateur -> SIAS : Récupération Téléopérations
        Concentrateur -> Répéteur : Téléopérations Capteurs
        Répéteur -> Capteur : Téléopérations Capteur
        note right : 6 téléopérations par an\n et par capteur
    end

    group Téléopérations Répéteurs
        Concentrateur -> SIAS : Récupération Téléopérations
        Concentrateur -> Répéteur : Téléopérations Répéteur
        note right : 6 téléopérations par an\n et par Répéteur
    end

    group Téléchargement capteur
        SIAS -> Concentrateur : Firmwares Capteurs
        note right : 6 packages en hypothèse
        Concentrateur -> Répéteur : Firmwares Capteurs
        Répéteur -> Capteur : Firmware Capteur
        note right : 3 téléchargements sur\n la durée de vie
    end

    group téléchargement Répéteur
        SIAS -> Concentrateur : Firmware Répéteur
        Concentrateur -> Répéteur : Firmware Répéteur
        note right : 3 téléchargements sur\n la durée de vie
    end

    group Fonction en propre du répéteur
        Répéteur -> Concentrateur : Trames de supervision
        note right : une par jour
        Répéteur -> Répéteur : 2s de traitements par jour\ pour fonctions propres
    end

    group Interventions en local
        MOBx -> Répéteur : Chgt de Paramètres
        note right : 3 programmations sur la durée\n de vie (hors pose)
        MOBx -> Répéteur : Chgt de Firmware
        note right : 3 téléchargements en local sur la\n durée de vie
    end

    loop toute les 15 mn
        Concentrateur -> SIAS : Messages reçus
    end