#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_mad_client

EXTRA_COMPONENT_DIRS := C:/Alain/msys32/home/Robin/GliderThrow_Meter/extra_components

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(IDF_PATH)/make/project.mk

