#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_mad_client

EXTRA_COMPONENT_DIRS := $(PROJECT_PATH)/GliderThrow_Meter/extra_components

COMPONENT_ADD_INCLUDEDIRS := components/include

PROJECT_VER="1.0.0"

include $(IDF_PATH)/make/project.mk