#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
# Version History :
#	- 23/05/2019, version 1.0.1 - new gpio management
#

PROJECT_NAME := esp_mad_server

EXTRA_COMPONENT_DIRS := C:/esp-idf/msys32/home/Eliot/esp/GliderThrow_Meter/extra_components

COMPONENT_ADD_INCLUDEDIRS := components/include

PROJECT_VER="1.0.1"

include $(IDF_PATH)/make/project.mk