#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_mad_server

EXTRA_COMPONENT_DIRS := C:/esp-idf/msys32/home/OU1179/esp/extra_components

COMPONENT_ADD_INCLUDEDIRS := components/include

include $(IDF_PATH)/make/project.mk

